function Model$$module$js$meshes(props) {
  /** @const */ 
  var $jscomp$destructuring$var0 = (0,shadow.js.shim.module$$react_three$drei.useGLTF)("https://github.com/pkingstonxyz/twentyfourtyate/raw/main/TwentyFourtyAte/assets/models/meshes.glb");
  /** @const */ 
  var nodes = $jscomp$destructuring$var0.nodes;
  /** @const */ 
  var materials = $jscomp$destructuring$var0.materials;
  return shadow.js.shim.module$react.createElement("group", Object.assign({}, props, {dispose:null}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes.plate.geometry, material:nodes.plate.material, scale:[0.595, 0.039, 0.595]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["2mesh"].geometry, material:nodes["2mesh"].material, scale:[0.5, 0.064, 0.5]}), shadow.js.shim.module$react.createElement("mesh", 
  {castShadow:true, receiveShadow:true, geometry:nodes["2num"].geometry, material:nodes["2num"].material, scale:[0.5, 0.064, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["8num"].geometry, material:nodes["8num"].material, scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["16num"].geometry, material:nodes["16num"].material, scale:[0.473, 0.049, 0.473]}), 
  shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["32num"].geometry, material:nodes["32num"].material, scale:[0.452, 0.046, 0.452]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["64num"].geometry, material:nodes["64num"].material, scale:[0.221, 0.023, 0.221]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["128num"].geometry, material:nodes["128num"].material, 
  scale:[0.419, 0.043, 0.419]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["512num"].geometry, material:nodes["512num"].material, rotation:[0, 0, -0.071], scale:[0.5, 0.034, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["1024num"].geometry, material:nodes["1024num"].material, rotation:[-0.005, 0.003, -0.045], scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", 
  {castShadow:true, receiveShadow:true, geometry:nodes["2048num"].geometry, material:nodes["2048num"].material, scale:[0.548, 0.05, 0.548]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["4num"].geometry, material:nodes["4num"].material, scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["256num"].geometry, material:nodes["256num"].material, rotation:[0, -0.016, 
  Math.PI], scale:[0.5, 0.051, 0.405]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["4mesh"].geometry, material:nodes["4mesh"].material, scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["8mesh"].geometry, material:nodes["8mesh"].material, scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["16mesh"].geometry, 
  material:nodes["16mesh"].material, scale:[0.473, 0.049, 0.473]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["32mesh"].geometry, material:nodes["32mesh"].material, scale:[0.452, 0.046, 0.452]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["64mesh"].geometry, material:nodes["64mesh"].material, scale:[0.221, 0.023, 0.221]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, 
  receiveShadow:true, geometry:nodes["128mesh"].geometry, material:nodes["128mesh"].material, scale:[0.419, 0.043, 0.419]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["512mesh"].geometry, material:nodes["512mesh"].material, rotation:[0, 0, -0.071], scale:[0.5, 0.034, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["1024mesh"].geometry, material:nodes["1024mesh"].material, rotation:[-0.005, 
  0.003, -0.045], scale:[0.5, 0.051, 0.5]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["2048mesh"].geometry, material:nodes["2048mesh"].material, scale:[0.548, 0.05, 0.548]}), shadow.js.shim.module$react.createElement("mesh", {castShadow:true, receiveShadow:true, geometry:nodes["256mesh"].geometry, material:nodes["256mesh"].material, rotation:[0, -0.016, Math.PI], scale:[0.5, 0.051, 0.405]}));
}
shadow.js.shim.module$$react_three$drei.useGLTF.preload("https://github.com/pkingstonxyz/twentyfourtyate/raw/main/TwentyFourtyAte/assets/models/meshes.glb");
/** @const */ 
var module$js$meshes = {};
/** @const */ 
module$js$meshes.Model = Model$$module$js$meshes;

$CLJS.module$js$meshes=module$js$meshes;
//# sourceMappingURL=module$js$meshes.js.map
